### ISSUE TITLE
Should there be a "o-" before the namespace for each class

### ISSUE THREAD

**Issue by HammyNZ** [csshugs/objects.text-input#1]
I might be missing something but should there be a "o-" in the class name declarations e.g.
`.#{$inuit-text-input-namespace}o-text-input {`

Shouldn't it be like this instead:
`.#{$inuit-text-input-namespace}text-input {`

Its the same for the variations/modifiers and textarea options when enabled.

**Comment by csshugs** [comment]
@HammyNZ 
Yes, this is absolutely intended.
Have a look at [this article](http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/) for further explanation.

**Comment by HammyNZ** [comment]
Awesome - thanks for the link :) A good read.

But I still feel it may be incorrectly defined in your object. Looking at other examples of the inuit objects, they don't extend to these namespaces (e.g. `o-`, `c-` etc).
example: https://github.com/inuitcss/objects.media/blob/master/_objects.media.scss

Is that what the variable $inuit-text-input-namespace is possibly for - the ability to add on the preferred namespace for a project?

**Comment by csshugs** [comment]
@HammyNZ 

> example: https://github.com/inuitcss/objects.media/blob/master/_objects.media.scss

It is not implemented, yet (https://github.com/inuitcss/objects.media/pull/5). For all the other inuitcss objects are also open Pull Requests waiting to be merged in. 

Until then you can actually use, in the case of the media object for example, the `$inuit-media-namespace` variable. But these variables originally are intended to prevent naming conflicts when other classes of a different origin are involved than the inuitcss framework. For example some CMSs are spitting out classes you cannot change.
