### ISSUE TITLE
Issues with text areas

### ISSUE THREAD

**Issue by HammyNZ** [csshugs/objects.text-input#2]
When you use `.o-text-input` on an text area element, the height has a unexpected styling effect when there is multiple lines

When you enable `.o-textarea` and use it on the text area, you lose the padding that is around an input that uses `.o-text-input`

**Comment by HammyNZ** [comment]
I've forked and made some tweaks: https://github.com/HammyNZ/objects.text-input

I'm currently testing this out in a project... Will follow up with any issues with my tweaks

**Comment by csshugs** [comment]
@HammyNZ 

> When you use .o-text-input on an text area element, the height has a unexpected styling effect when there is multiple lines

`.o-text-input` is not supposed to be used on an `<textarea>` element. That's why the `.o-textarea` class is provided. 
But you are right. It looks a bit inconsistent as it is now. I consider refactoring this soon.
